# 🐳 Docker Compose - NestJS Stripe Notion WhatsApp
# version: '3.8'  # Removed obsolete version field

services:
  # ================================
  # Desarrollo Local
  # ================================
  nestjs-dev:
    build:
      context: .
      target: development
    container_name: nestjs-stripe-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - PORT=3000
      # Variables de Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      # Variables de Notion  
      - NOTION_SECRET=${NOTION_SECRET}
      - NOTION_CLIENTS_DATABASE_ID=${NOTION_CLIENTS_DATABASE_ID}
      - NOTION_PAYMENTS_DATABASE_ID=${NOTION_PAYMENTS_DATABASE_ID}
      - NOTION_CALENDAR_DATABASE_ID=${NOTION_CALENDAR_DATABASE_ID}
      # Variables de WhatsApp
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_FROM=${TWILIO_WHATSAPP_FROM}
      - USE_META_WHATSAPP_API=${USE_META_WHATSAPP_API}
    restart: unless-stopped
    networks:
      - nestjs-network

  # ================================
  # Test Environment 
  # ================================
  nestjs-test:
    build:
      context: .
      target: development
    container_name: nestjs-stripe-test
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - PORT=3000
      # Variables de Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      # Variables de Notion  
      - NOTION_SECRET=${NOTION_SECRET}
      - NOTION_CLIENTS_DATABASE_ID=${NOTION_CLIENTS_DATABASE_ID}
      - NOTION_PAYMENTS_DATABASE_ID=${NOTION_PAYMENTS_DATABASE_ID}
      - NOTION_CALENDAR_DATABASE_ID=${NOTION_CALENDAR_DATABASE_ID}
      # Variables de WhatsApp
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_FROM=${TWILIO_WHATSAPP_FROM}
      - USE_META_WHATSAPP_API=${USE_META_WHATSAPP_API}
    restart: unless-stopped
    networks:
      - nestjs-network

  # ================================
  # Production Environment
  # ================================
  nestjs-prod:
    build:
      context: .
      target: production
    container_name: nestjs-stripe-prod
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Variables de Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      # Variables de Notion  
      - NOTION_SECRET=${NOTION_SECRET}
      - NOTION_CLIENTS_DATABASE_ID=${NOTION_CLIENTS_DATABASE_ID}
      - NOTION_PAYMENTS_DATABASE_ID=${NOTION_PAYMENTS_DATABASE_ID}
      - NOTION_CALENDAR_DATABASE_ID=${NOTION_CALENDAR_DATABASE_ID}
      # Variables de WhatsApp
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_FROM=${TWILIO_WHATSAPP_FROM}
      - USE_META_WHATSAPP_API=${USE_META_WHATSAPP_API}
    restart: unless-stopped
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

# ================================
# Volúmenes
# ================================
volumes:
  node_modules: 