version: '3.8'

services:
  # Aplicación NestJS
  nestjs-stripe:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs-stripe-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Solo logs para producción
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



networks:
  nestjs-network:
    driver: bridge 