# Configuración de Fly.io para NestJS Stripe Notion Automation
app = "nestjs-stripe-notion"
primary_region = "mia"  # Miami - cambiar según tu región preferida

[experimental]
auto_rollback = true

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "30s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/health"
protocol = "http"
tls_skip_verify = false

[http_service.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[http_service.http_options.headers]]
name = "X-Frame-Options"
value = "DENY"

[[http_service.http_options.headers]]
name = "X-Content-Type-Options"
value = "nosniff"

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[[restart]]
policy = "on-failure"
max_restarts = 10 